import { Icons } from "@/components/icons";
import { NavItem, SidebarNavItem } from "@/types";

export type User = {
  id: number;
  name: string;
  company: string;
  role: string;
  verified: boolean;
  status: string;
};
export const users: User[] = [
  {
    id: 1,
    name: "Candice Schiner",
    company: "Dell",
    role: "Frontend Developer",
    verified: false,
    status: "Active",
  },
  {
    id: 2,
    name: "John Doe",
    company: "TechCorp",
    role: "Backend Developer",
    verified: true,
    status: "Active",
  },
  {
    id: 3,
    name: "Alice Johnson",
    company: "WebTech",
    role: "UI Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 4,
    name: "David Smith",
    company: "Innovate Inc.",
    role: "Fullstack Developer",
    verified: false,
    status: "Inactive",
  },
  {
    id: 5,
    name: "Emma Wilson",
    company: "TechGuru",
    role: "Product Manager",
    verified: true,
    status: "Active",
  },
  {
    id: 6,
    name: "James Brown",
    company: "CodeGenius",
    role: "QA Engineer",
    verified: false,
    status: "Active",
  },
  {
    id: 7,
    name: "Laura White",
    company: "SoftWorks",
    role: "UX Designer",
    verified: true,
    status: "Active",
  },
  {
    id: 8,
    name: "Michael Lee",
    company: "DevCraft",
    role: "DevOps Engineer",
    verified: false,
    status: "Active",
  },
  {
    id: 9,
    name: "Olivia Green",
    company: "WebSolutions",
    role: "Frontend Developer",
    verified: true,
    status: "Active",
  },
  {
    id: 10,
    name: "Robert Taylor",
    company: "DataTech",
    role: "Data Analyst",
    verified: false,
    status: "Active",
  },
];

export type Employee = {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  phone: string;
  gender: string;
  date_of_birth: string; // Consider using a proper date type if possible
  street: string;
  city: string;
  state: string;
  country: string;
  zipcode: string;
  longitude?: number; // Optional field
  latitude?: number; // Optional field
  job: string;
  profile_picture?: string | null; // Profile picture can be a string (URL) or null (if no picture)
};

export const navItems: NavItem[] = [
  {
    title: "Dashboard",
    href: "/dashboard",
    icon: "dashboard",
    label: "Dashboard",
    role: ["user", "admin", "guest", "master-admin"],
  },
  {
    title: "Profile",
    href: "/dashboard/profile",
    icon: "profile",
    label: "profile",
    role: ["user", "admin", "guest", "master-admin"],
  },
  {
    title: "Booking",
    href: "/dashboard/booking",
    icon: "booking",
    label: "booking",
    role: ["user"],
  },
  {
    title: "Booking management",
    href: "/dashboard/booking-management",
    icon: "booking",
    label: "booking-management",
    role: ["admin", "master-admin"],
  },
  /*   {
    title: "Cargo",
    href: "/dashboard/cargo",
    icon: "cargo",
    label: "cargo",
  }, */
  {
    title: "Container",
    href: "/dashboard/container",
    icon: "container",
    label: "container",
    role: ["admin", "master-admin"],
  },
  /*   {
    title: "Tracking",
    href: "/dashboard/tracking",
    icon: "tracking",
    label: "tracking",
  }, */
  /*   {
    title: "Schedule",
    href: "/dashboard/schedule",
    icon: "calendar",
    label: "schedule",
  }, */
  {
    title: "Vessel",
    href: "/dashboard/vessel",
    icon: "ship",
    label: "schedule",
    role: ["admin", "master-admin"],
  },

  {
    title: "Route",
    href: "/dashboard/route",
    icon: "route",
    label: "route",
    role: ["admin", "master-admin"],
  },
  {
    title: "Port sequence",
    href: "/dashboard/port-sequence",
    icon: "route",
    label: "route",
    role: ["admin", "master-admin"],
  },
  {
    title: "Port",
    href: "/dashboard/port",
    icon: "port",
    label: "port",
    role: ["admin", "master-admin"],
  },
  /*   {
    title: "Employee",
    href: "/dashboard/employee",
    icon: "employee",
    label: "employee",
  }, */
  {
    title: "User",
    href: "/dashboard/user",
    icon: "user",
    label: "user",
    role: ["master-admin"],
  },

  /*   {
    title: "Kanban",
    href: "/dashboard/kanban",
    icon: "kanban",
    label: "kanban",
  }, */
  /*   {
    title: "Login",
    href: "/sigin",
    icon: "login",
    label: "login",
  }, */
  /*   {
    title: "test",
    href: "/dashboard/test",

    label: "test",
  }, */
];

export const countryList: {
  name: string;
  countryCode: string;
}[] =
  /* [
  { name: "Afghanistan", countryCode: "AF" },
  { name: "Albania", countryCode: "AL" },
  { name: "Algeria", countryCode: "DZ" },
  { name: "Andorra", countryCode: "AD" },
  { name: "Angola", countryCode: "AO" },
  { name: "Antigua and Barbuda", countryCode: "AG" },
  { name: "Argentina", countryCode: "AR" },
  { name: "Armenia", countryCode: "AM" },
  { name: "Australia", countryCode: "AU" },
  { name: "Austria", countryCode: "AT" },
  { name: "Azerbaijan", countryCode: "AZ" },
  { name: "Bahamas", countryCode: "BS" },
  { name: "Bahrain", countryCode: "BH" },
  { name: "Bangladesh", countryCode: "BD" },
  { name: "Barbados", countryCode: "BB" },
  { name: "Belarus", countryCode: "BY" },
  { name: "Belgium", countryCode: "BE" },
  { name: "Belize", countryCode: "BZ" },
  { name: "Benin", countryCode: "BJ" },
  { name: "Bhutan", countryCode: "BT" },
  { name: "Bolivia", countryCode: "BO" },
  { name: "Bosnia and Herzegovina", countryCode: "BA" },
  { name: "Botswana", countryCode: "BW" },
  { name: "Brazil", countryCode: "BR" },
  { name: "Brunei", countryCode: "BN" },
  { name: "Bulgaria", countryCode: "BG" },
  { name: "Burkina Faso", countryCode: "BF" },
  { name: "Burundi", countryCode: "BI" },
  { name: "Cabo Verde", countryCode: "CV" },
  { name: "Cambodia", countryCode: "KH" },
  { name: "Cameroon", countryCode: "CM" },
  { name: "Canada", countryCode: "CA" },
  { name: "Central African Republic", countryCode: "CF" },
  { name: "Chad", countryCode: "TD" },
  { name: "Chile", countryCode: "CL" },
  { name: "China", countryCode: "CN" },
  { name: "Colombia", countryCode: "CO" },
  { name: "Comoros", countryCode: "KM" },
  { name: "Congo", countryCode: "CG" },
  { name: "Costa Rica", countryCode: "CR" },
  { name: "Croatia", countryCode: "HR" },
  { name: "Cuba", countryCode: "CU" },
  { name: "Cyprus", countryCode: "CY" },
  { name: "Czechia", countryCode: "CZ" },
  { name: "Democratic Republic of the Congo", countryCode: "CD" },
  { name: "Denmark", countryCode: "DK" },
  { name: "Djibouti", countryCode: "DJ" },
  { name: "Dominica", countryCode: "DM" },
  { name: "Dominican Republic", countryCode: "DO" },
  { name: "East Timor", countryCode: "TL" },
  { name: "Ecuador", countryCode: "EC" },
  { name: "Egypt", countryCode: "EG" },
  { name: "El Salvador", countryCode: "SV" },
  { name: "Equatorial Guinea", countryCode: "GQ" },
  { name: "Eritrea", countryCode: "ER" },
  { name: "Estonia", countryCode: "EE" },
  { name: "Eswatini", countryCode: "SZ" },
  { name: "Ethiopia", countryCode: "ET" },
  { name: "Fiji", countryCode: "FJ" },
  { name: "Finland", countryCode: "FI" },
  { name: "France", countryCode: "FR" },
  { name: "Gabon", countryCode: "GA" },
  { name: "Gambia", countryCode: "GM" },
  { name: "Georgia", countryCode: "GE" },
  { name: "Germany", countryCode: "DE" },
  { name: "Ghana", countryCode: "GH" },
  { name: "Greece", countryCode: "GR" },
  { name: "Grenada", countryCode: "GD" },
  { name: "Guatemala", countryCode: "GT" },
  { name: "Guinea", countryCode: "GN" },
  { name: "Guinea-Bissau", countryCode: "GW" },
  { name: "Guyana", countryCode: "GY" },
  { name: "Haiti", countryCode: "HT" },
  { name: "Honduras", countryCode: "HN" },
  { name: "Hungary", countryCode: "HU" },
  { name: "Iceland", countryCode: "IS" },
  { name: "India", countryCode: "IN" },
  { name: "Indonesia", countryCode: "ID" },
  { name: "Iran", countryCode: "IR" },
  { name: "Iraq", countryCode: "IQ" },
  { name: "Ireland", countryCode: "IE" },
  { name: "Israel", countryCode: "IL" },
  { name: "Italy", countryCode: "IT" },
  { name: "Ivory Coast", countryCode: "CI" },
  { name: "Jamaica", countryCode: "JM" },
  { name: "Japan", countryCode: "JP" },
  { name: "Jordan", countryCode: "JO" },
  { name: "Kazakhstan", countryCode: "KZ" },
  { name: "Kenya", countryCode: "KE" },
  { name: "Kiribati", countryCode: "KI" },
  { name: "Kuwait", countryCode: "KW" },
  { name: "Kyrgyzstan", countryCode: "KG" },
//  { name: "Laos", countryCode: "LA" },
//  { name: "Latvia", countryCode: "LV" },
//  { name: "Lebanon", countryCode: "LB" },
  { name: "Lesotho", countryCode: "LS" },
  { name: "Liberia", countryCode: "LR" },
  { name: "Libya", countryCode: "LY" },
  { name: "Liechtenstein", countryCode: "LI" },
  { name: "Lithuania", countryCode: "LT" },
  { name: "Luxembourg", countryCode: "LU" },
  { name: "Madagascar", countryCode: "MG" },
  { name: "Malawi", countryCode: "MW" },
  { name: "Malaysia", countryCode: "MY" },
  { name: "Maldives", countryCode: "MV" },
  { name: "Mali", countryCode: "ML" },
  { name: "Malta", countryCode: "MT" },
  { name: "Marshall Islands", countryCode: "MH" },
  { name: "Mauritania", countryCode: "MR" },
  { name: "Mauritius", countryCode: "MU" },
  { name: "Mexico", countryCode: "MX" },
  { name: "Micronesia", countryCode: "FM" },
  { name: "Moldova", countryCode: "MD" },
  { name: "Monaco", countryCode: "MC" },
  { name: "Mongolia", countryCode: "MN" },
  { name: "Montenegro", countryCode: "ME" },
  { name: "Morocco", countryCode: "MA" },
  { name: "Mozambique", countryCode: "MZ" },
  { name: "Myanmar", countryCode: "MM" },
  { name: "Namibia", countryCode: "NA" },
  { name: "Nauru", countryCode: "NR" },
  { name: "Nepal", countryCode: "NP" },
  { name: "Netherlands", countryCode: "NL" },
  { name: "New Zealand", countryCode: "NZ" },
  { name: "Nicaragua", countryCode: "NI" },
  { name: "Niger", countryCode: "NE" },
  { name: "Nigeria", countryCode: "NG" },
  { name: "North Korea", countryCode: "KP" },
  { name: "North Macedonia", countryCode: "MK" },
  { name: "Norway", countryCode: "NO" },
  { name: "Oman", countryCode: "OM" },
  { name: "Pakistan", countryCode: "PK" },
  { name: "Palau", countryCode: "PW" },
  { name: "Palestine", countryCode: "PS" },
  { name: "Panama", countryCode: "PA" },
  { name: "Papua New Guinea", countryCode: "PG" },
  { name: "Paraguay", countryCode: "PY" },
  { name: "Peru", countryCode: "PE" },
  { name: "Philippines", countryCode: "PH" },
  { name: "Poland", countryCode: "PL" },
  { name: "Portugal", countryCode: "PT" },
  { name: "Qatar", countryCode: "QA" },
  { name: "Romania", countryCode: "RO" },
  { name: "Russia", countryCode: "RU" },
  { name: "Rwanda", countryCode: "RW" },
  { name: "Saint Kitts and Nevis", countryCode: "KN" },
  { name: "Saint Lucia", countryCode: "LC" },
  { name: "Saint Vincent and the Grenadines", countryCode: "VC" },
  { name: "Samoa", countryCode: "WS" },
  { name: "San Marino", countryCode: "SM" },
  { name: "Sao Tome and Principe", countryCode: "ST" },
  { name: "Saudi Arabia", countryCode: "SA" },
  { name: "Senegal", countryCode: "SN" },
  { name: "Serbia", countryCode: "RS" },
  { name: "Seychelles", countryCode: "SC" },
  { name: "Sierra Leone", countryCode: "SL" },
  { name: "Singapore", countryCode: "SG" },
  { name: "Slovakia", countryCode: "SK" },
  { name: "Slovenia", countryCode: "SI" },
  { name: "Solomon Islands", countryCode: "SB" },
  { name: "Somalia", countryCode: "SO" },
  { name: "South Africa", countryCode: "ZA" },
  { name: "South Korea", countryCode: "KR" },
  { name: "South Sudan", countryCode: "SS" },
  { name: "Spain", countryCode: "ES" },
  { name: "Sri Lanka", countryCode: "LK" },
  { name: "Sudan", countryCode: "SD" },
  { name: "Suriname", countryCode: "SR" },
  { name: "Sweden", countryCode: "SE" },
  { name: "Switzerland", countryCode: "CH" },
  { name: "Syria", countryCode: "SY" },
  { name: "Tajikistan", countryCode: "TJ" },
  { name: "Tanzania", countryCode: "TZ" },
  { name: "Thailand", countryCode: "TH" },
  { name: "Togo", countryCode: "TG" },
  { name: "Tonga", countryCode: "TO" },
  { name: "Trinidad and Tobago", countryCode: "TT" },
  { name: "Tunisia", countryCode: "TN" },
  { name: "Turkey", countryCode: "TR" },
  { name: "Turkmenistan", countryCode: "TM" },
  { name: "Tuvalu", countryCode: "TV" },
  { name: "Uganda", countryCode: "UG" },
  { name: "Ukraine", countryCode: "UA" },
  { name: "United Arab Emirates", countryCode: "AE" },
  { name: "United Kingdom", countryCode: "GB" },
  { name: "United States", countryCode: "US" },
  { name: "Uruguay", countryCode: "UY" },
  { name: "Uzbekistan", countryCode: "UZ" },
  { name: "Vanuatu", countryCode: "VU" },
  { name: "Vatican City", countryCode: "VA" },
  { name: "Venezuela", countryCode: "VE" },
  { name: "Vietnam", countryCode: "VN" },
  { name: "Yemen", countryCode: "YE" },
  { name: "Zambia", countryCode: "ZM" },
  { name: "Zimbabwe", countryCode: "ZW" },
];
 */
  [
    { name: "Australia", countryCode: "AU" },
    { name: "Bahamas", countryCode: "BS" },
    { name: "Bangladesh", countryCode: "BD" },
    { name: "Belgium", countryCode: "BE" },
    { name: "Brazil", countryCode: "BR" },
    { name: "Canada", countryCode: "CA" },
    { name: "China", countryCode: "CN" },
    { name: "Denmark", countryCode: "DK" },
    { name: "Egypt", countryCode: "EG" },
    { name: "France", countryCode: "FR" },
    { name: "Germany", countryCode: "DE" },
    { name: "India", countryCode: "IN" },
    { name: "Indonesia", countryCode: "ID" },
    { name: "Italy", countryCode: "IT" },
    { name: "Japan", countryCode: "JP" },
    { name: "Malaysia", countryCode: "MY" },
    { name: "Mexico", countryCode: "MX" },
    { name: "Netherlands", countryCode: "NL" },
    { name: "Norway", countryCode: "NO" },
    { name: "Panama", countryCode: "PA" },
    { name: "Philippines", countryCode: "PH" },
    { name: "Portugal", countryCode: "PT" },
    { name: "Russia", countryCode: "RU" },
    { name: "Saudi Arabia", countryCode: "SA" },
    { name: "Singapore", countryCode: "SG" },
    { name: "South Africa", countryCode: "ZA" },
    { name: "South Korea", countryCode: "KR" },
    { name: "Spain", countryCode: "ES" },
    { name: "Sweden", countryCode: "SE" },
    { name: "Taiwan", countryCode: "TW" },
    { name: "Thailand", countryCode: "TH" },
    { name: "Turkey", countryCode: "TR" },
    { name: "United Kingdom", countryCode: "GB" },
    { name: "United States", countryCode: "US" },
    { name: "United Arab Emirates", countryCode: "AE" },

    { name: "Vietnam", countryCode: "VN" },
  ];
